spring:
  application:
    name: PigeonSkyRace

  datasource:
    url: jdbc:postgresql://localhost:5432/pigeonSky
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

logging:
  level:
    root: DEBUG
    org.springframework.jdbc: DEBUG

secret:
