server:
    port: 8443
    ssl:
      enabled: true
      key-store: classpath:keystore.p12
      key-store-password: pass123
      key-store-type: PKCS12
      key-alias: mykey
spring:
  application:
    name: PigeonSkyRace
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-boot-client
            client-secret: ${SPRING_SECRET}
            authorization-grant-type: authorization_code
            scope: openid,profile,email , roles
            redirect-uri:  http://localhost:8082/login/oauth2/code/keycloak
            issuer-uri: http://localhost:8082/realms/spring-boot-realm
        provider:
          keycloak:
            token-uri: http://localhost:8082/realms/spring-boot-realm/protocol/openid-connect/token
            authorization-uri: http://localhost:8082/realms/spring-boot-realm/protocol/openid-connect/auth
logging:
  level:
    root: DEBUG
    org.springframework.jdbc: DEBUG

keycloak:
  auth-server-url:  http://localhost:8082/realms/spring-boot-realm
  realm: spring-boot-realm
  resource : spring-boot-client
  credentials:
    secret: ${SPRING_SECRET}
  public-client: false
  bearer-only: false 
  use-resource-role-mappings: true

  security-constraints:
    - authRoles:
        - USER
        - ADMIN
      urlPattern: /* 
